CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL UNIQUE,
                            description VARCHAR(500),
                            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          sku VARCHAR(100) NOT NULL UNIQUE,
                          name VARCHAR(200) NOT NULL,
                          description TEXT,
                          price NUMERIC(19, 2) NOT NULL CHECK (price >= 0),
                          currency VARCHAR(3) NOT NULL,
                          image_url VARCHAR(500),
                          category_id BIGINT NOT NULL,
                          active BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_products_category
                              FOREIGN KEY (category_id)
                                  REFERENCES categories(id)
);

CREATE TABLE inventory (
                           product_id BIGINT PRIMARY KEY,
                           available_quantity INTEGER NOT NULL DEFAULT 0
                               CHECK (available_quantity >= 0),
                           reserved_quantity INTEGER NOT NULL DEFAULT 0
                               CHECK (reserved_quantity >= 0),
                           version BIGINT NOT NULL DEFAULT 0,

                           CONSTRAINT fk_inventory_product
                               FOREIGN KEY (product_id)
                                   REFERENCES products(id)
);